# Generated by Django 3.0.7 on 2020-07-03 15:29

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 3, 15, 29, 18, 410601, tzinfo=utc), verbose_name='date published'),
        ),
    ]
